term.setBackgroundColor(colors.white)
term.setTextColor(colors.pink)
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("    ___  ___  _  _ _  _ ____ _  ___    ____ ____     ")
print("   |    |     |\\/| |  | [__  | |       |  | [__      ")
print("   |___ |___  |  | |__| ___] | |___    |__| ___]     ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
print("                BY Glass Technology                  ")
print("                                                      ")
print("                                                      ")
print("                                                      ")
