shell.run("clear")
term.write("+========================+")
print("")
sleep(0.2)
term.write("| Copyright(c)2022 GLASS |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|      ccmusicUI2.1      |")
print("")
sleep(0.2)
term.write("|      by mao_liuli      |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|    Technical advice:   |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|   crlash qq:596931985  |")
print("")
sleep(0.2)
term.write("| Tairitsu qq:2649111464 |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|  Song list available:  |")
print("")
sleep(0.2)
term.write("|old_black  qq:1301521064|")
print("")
sleep(0.2)
term.write("| Mao_liuli qq:180877430 |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|                        |")
print("")
sleep(0.2)
term.write("|  qq discussion group:  |")
print("")
sleep(0.2)
term.write("|       756933770        |")
print("")
term.write("+========================+")
print("")
sleep(0.2)