term.setBackgroundColor(colors.white)
term.setTextColor(colors.pink)
print("                                                                                        ")
print("                                                                                        ")
print("                                                                                        ")
print("                                                                                        ")
print("                                                                                        ")
print("   _  _ _  _ ____ + ____                                                                ")
print("   |\\/| |  | [__  | |                                                                  ")
print("   |  | |__| ___] | |___                                                                ")
print("       ____    _____                                                                    ")
print("      / __ \\  / ____|                                                                  ")
print("      ||  ||  | (___                                                                    ")
print("      ||  ||  \\___  \\                                                                 ")
print("      ||__||  ____) |                                                                   ")
print("      \\____/ |______/                                                                  ")
print("                                                                                        ")
print("                                                                                        ")
print("                                                                                        ")
print("                                                                                        ")
print("                                                                                        ")
print("    By:Glass Technology                                                                 ")
print("     ccmusic OS  5.5.1                                                                  ")

term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
